version: "3"
services:
  react-app:
    build: ./messaging_client
    image: react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    build: ./Messaging_Api
    image: server-api
    ports:
      - "3001:3001"
    networks:
      - mern-app
    
    
  
networks:
  mern-app:
    driver: bridge